demo/fileserver/fileserver/urls.py
# from django.contrib import admin
# from django.urls import path, include
from fileupload import views as fileupload_views

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', fileupload_views.home, name='home'),
    
# ]


# urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', fileupload_views.home, name='home'),
    path('fileupload/', include('fileupload.urls', namespace='fileupload')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo/fileserver/fileupload/urls.py
from django.urls import path
from . import views

app_name = 'fileupload'

urlpatterns = [
    path('upload/', views.upload_file, name='upload_file'),
    path('check/', views.check_file, name='check_file'),
]

demo/fileserver/fileupload/models.py
from django.db import models

# Create your models here.

demo/fileserver/fileupload/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponse
from django.core.files.storage import FileSystemStorage
from code_unit import data_interface

def upload_file(request):
    if request.method == 'POST' and request.FILES['file']:
        file = request.FILES['file']
        fs = FileSystemStorage()
        file_content = file.read()

        

        # fs.save(file.name, file)
        
        # print(file_content)
        # print(f"SHA1 is :{sha1_code}")
        print(type(file))
        
        """_summary_
        do something:
        存取文件通过hash加密,
        以HASH值存取文件名称,
        并用HASH为密钥使用SM4加密算法加密文件。
        Returns:
            _type_: _description_
            byte : sha1_code 文件的hash结果
            state : 是否存在文件的状态
        """
        #example
        # import hashlib
        # sha1_code =hashlib.sha1(file_content).hexdigest()
        # from gmssl import sm4
        # b = sm4.CryptSM4()
        # print(sha1_code)
        # import binascii
        # b.set_key(binascii.a2b_hex(sha1_code),mode=sm4.SM4_ENCRYPT)
        # encode_msg= b.crypt_cbc(bytes.fromhex("F"*32),file_content)
        # import os
        # print(os.getcwd())
        # try:
        #     os.chdir('media')
        # except:
        #     pass
        # try: 
        #     f=open(sha1_code,"r") 
        #     print("文件存在")
        #     state=1
        # except FileNotFoundError:

        #     f=open(sha1_code,"wb")
        #     f.write(encode_msg)
        #     state=0
        
        # #example end
        # pass
        sha1_code,state = data_interface.encrypt(file_content)
        state="Success" if state==0 else "Failed"
        
        return render(request, 'fileupload/upload_success.html',{"sha1":sha1_code,"state":state})
    return render(request, 'fileupload/upload.html')  



def check_file(request):
    if request.method == 'POST' and request.POST.get('filename'):
        filename = request.POST['filename']
        fs = FileSystemStorage()
        file_exists = fs.exists(filename)
        if file_exists:
            # import os
            # try:
            #     os.chdir('media')
            # except:
            #     pass
            # from gmssl import sm4
            # b = sm4.CryptSM4()
            # print(filename)
            # import binascii
            # b.set_key(binascii.a2b_hex(filename),mode=sm4.SM4_DECRYPT)
            # # encode_msg= b.crypt_cbc(bytes.fromhex("F"*32),file_content)
            # print(fs.url(filename))
            # decode_msg=b.crypt_cbc(bytes.fromhex("F"*32),open(filename,"rb").read())
            # print(decode_msg)
            # with open("temp","wb") as f:
            #     f.write(decode_msg)
            data_interface.decrypt(filename)
            return render(request, 'fileupload/check.html', {'filename': filename, 'file_exists': file_exists, 'download_url': fs.url("temp")})
        else:
            return render(request, 'fileupload/check.html', {'filename': filename, 'file_exists': file_exists})
    return render(request, 'fileupload/check.html')
 

 
def home(request):
    return render(request, 'fileupload/home.html')

demo/fileserver/fileupload/templates/fileupload/check.html
<body>
  <div class="container">
    <h1>Welcome to the EFRS</h1>

    <div class="button-container">
      <form class="form-container" method="post" action="{% url 'fileupload:check_file' %}">
        {% csrf_token %}
        <input type="text" name="filename" placeholder="Enter filename">
        <button type="submit">Check</button>
      </form>
      
      <div class="result-container">
        {% if filename %}
          <h3>Filename: {{ filename }}</h3>
          {% if file_exists %}
            <p>The file exists.</p>
            <a href="{{ download_url }}">Download</a>
          {% else %}
            <p>The file does not exist.</p>
          {% endif %}
        {% endif %}
      </div>
      
      <button class="goback-button" onclick="goBack()">Go Back</button>
    </div>
  </div>
</body>


<!-- <button onclick="goBack()">Go Back</button>/ -->

<script>
function goBack() {
  window.location.href='/';
  // window.history.back();
}
</script>

  



<style>
  body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 100vh;
    font-family: Arial, sans-serif;
  }
  
  h1 {
    font-size: 48px;
    margin-bottom: 40px;
  }
  
  .form-container {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  
  .form-container input[type="text"] {
    padding: 8px;
    font-size: 16px;
    border: 1px solid #ccc;
    border-radius: 4px;
  }
  
  .form-container button[type="submit"] {
    padding: 8px 16px;
    font-size: 16px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  
  .result-container {
    margin-top: 20px;
    text-align: center;
  }
  
  .result-container h3 {
    font-size: 24px;
  }
  
  .result-container p {
    font-size: 16px;
  }
  
  .result-container a {
    display: inline-block;
    padding: 8px 16px;
    font-size: 16px;
    text-decoration: none;
    background-color: #007bff;
    color: #fff;
    border-radius: 4px;
    transition: background-color 0.3s ease;
  }
  
  .result-container a:hover {
    background-color: #0056b3;
  }
  
  .goback-button {
    margin-top: 20px;
    padding: 8px 16px;
    font-size: 16px;
    background-color: #a1f1f1;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  </style>
  

demo/fileserver/fileupload/templates/fileupload/home.html
<body>
    <div class="container">
      <h1>Welcome to the EFRS</h1>
  
      <div class="button-container">
        <a href="{% url 'fileupload:upload_file' %}">Upload File</a>
        <a href="{% url 'fileupload:check_file' %}">Check File</a>
      </div>
    </div>
  </body>
  



<style>
    body {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      height: 100vh;
      font-family: Arial, sans-serif;
    }
    
    h1 {
      font-size: 48px;
      margin-bottom: 40px;
    }
    
    .button-container {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 20px;
    }
    
    .button-container a {
      display: inline-block;
      padding: 12px 24px;
      font-size: 20px;
      text-decoration: none;
      background-color: #007bff;
      color: #fff;
      border-radius: 4px;
      transition: background-color 0.3s ease;
    }
    
    .button-container a:hover {
      background-color: #0056b3;
    }
    </style>
    

demo/fileserver/fileupload/templates/fileupload/upload.html
<!DOCTYPE html>
<html>
<head>
  <title>Please File Upload</title>
  <style>
    body {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      height: 100vh;
      font-family: Arial, sans-serif;
    }
    
    h1 {
      font-size: 32px;
      margin-bottom: 20px;
    }
    
    .form-container {
      display: flex;
      flex-direction: column;
      gap: 10px;
      align-items: center;
    }
    
    .custom-file-input {
      position: relative;
      overflow: hidden;
      display: inline-block;
      padding: 8px 16px;
      font-size: 16px;
      background-color: #007bff;
      color: #fff;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      position: absolute;
      right: 400px;
      width: 300px;
      border: 3px solid green;
    }
    
    .custom-file-input input[type="file"] {
      position: absolute;
      top: 0;
      right: 0;
      margin: 0;
      padding: 0;
      font-size: 100px;
      cursor: pointer;
      opacity: 0;
      margin: auto;
      border: 3px solid green;
    }
    
    .submit-button {
      padding: 10px 20px;
      font-size: 16px;
      background-color: #007bff;
      color: #fff;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      margin: auto;
      border: 3px solid green;
      position: absolute;
      right: 50%;
      width: 100px;
      border: 3px solid green;
    }
    
    .goback-button {
      margin-top: 20px;
      padding: 8px 16px;
      font-size: 16px;
      background-color: #a1f1f1;
      color: #fff;
      border-radius: 4px;
      cursor: pointer;
      border: 3px solid green;
      text-align: center;
    }
    
    input[type="file"] {
      display: none;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Please Upload File</h1>
    <div class="form-container">
      <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- <label for="file-input" class="custom-file-input">Choose File</label>
        <input id="file-input" type="file" name="file" class="hidden-input">
        <button class="submit-button" type="submit">Upload</button> -->
        <label for="file-input" >Choose File</label>
        <input id="file-input" type="file" name="file">
        <button type="submit">Upload</button>
      </form>
    </div>
    <button class="goback-button" onclick="goBack()">Go Back</button>
  </div>
</body>
</html>

<script>
  function goBack() {
    window.location.href='/';
  }
</script>

demo/fileserver/fileupload/templates/fileupload/upload_success.html
<body>
  <div class="container">
    <h1>File uploaded {{state}}</h1>
    <div class="button-container">
      {% if state == "Success" %}
        <h1>SHA-1: {{ sha1 }}</h1>
      {% endif %}
      <button class="goback-button" onclick="goBack()">Go Back</button>
    </div>
  </div>
</body>

<script>
function goBack() {
  window.location.href='/';
}
</script>

<style>
.goback-button {
  background-color: #a1f1f1;
  color: white;
  padding: 10px 20px;
  border: none;
  cursor: pointer;
  font-size: 16px;
}
</style>

<style>
body {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-family: Arial, sans-serif;
}

h1 {
  font-size: 48px;
  margin-bottom: 40px;
}

.button-container {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 20px;
}

.button-container a {
  display: inline-block;
  padding: 12px 24px;
  font-size: 20px;
  text-decoration: none;
  background-color: #007bff;
  color: #fff;
  border-radius: 4px;
  transition: background-color 0.3s ease;
}

.button-container a:hover {
  background-color: #0056b3;
}
</style>